pipeline {
    agent any
    stages {
        stage("Clean up")  {
          steps {
              deleteDir()
          }
        }
        stage("Clone Repo") {
            steps {	
		    echo "START"
		    git branch: 'main', url: 'https://github.com/trietnguyenk16-nkt/django-poc.git'
		    echo "END"
		    sh "pwd"
		    sh "ls -a"
		    //sh "python -v"
		    sh "yum install -y python3.8 python3.8-venv sqlite3"
		    sh "python -v"
		    //sh "cd workspace/${env.JOB_NAME}"
		    //echo pwd
		    //dir("workspace/${env.JOB_NAME}") {
			    //echo pwd
			    //sh "python -v"
		    //}
            }
        }
    }
}
