pipeline {
    agent any
    stages {
        stage("Source Code Management")  {
          steps {
              git branch: 'main', url: 'https://github.com/trietnguyenk16-nkt/django-poc.git' 
          }
        }
        stage("Installed libraries") {
            steps {	
		    sh "sudo yum install -y python3.8 python3.8-venv sqlite3 || true"
		    sh "python3 -m venv env"
		    sh "source env/bin/activate"
		    sh "python -m pip install -U pip 'django'"
            }
        }
    }
}
