pipeline {
    agent any
	parameters {
		booleanParam(defaultValue: false, description: "Enable Service?", name: "myBoolean")
		string(defaultValue: "Testing", description: "Which Environment?", name: "deployEnv")
		choice(choices: ["PRODD", "DEV", "QA"], description: "Environment choice", name: "envChoice")

	}
    stages {
        stage("Clean up")  {
          steps {
              deleteDir()
          }
        }
        stage("Clone Repo") {
            steps {
		    echo "clone step test"
		    echo "booleanParam is set to: ${params.myBoolean}"
		    echo "string is set to: ${params.deployEnv}"  
		    echo "choice is set to: ${params.envChoice}"
                //sh git clone "https://github.com/trietnguyenk16-nkt/django-poc.git"
                
            }
        }
        stage("Build") {
            steps {
		    echo "build step"
                // dir the same cd
                //dir("simple-java-maven-app") {
                    //sh "mvn clean install"
                //}
            }
        }
		stage("Test") {
			steps {
				echo "test step"
				//dir("simple-java-maven-app")
				//{
                    //sh "mvn test"
                //}
			}
		}
    }
}
